### ISSUE TITLE
[BUG]: Leak after AttributeError in class with shared_ptr member

### ISSUE THREAD

**Issue by jaicher** [wjakob/nanobind#376]
### Problem description

I have a class Parent with a shared_ptr to an instance of class Member. If I have an AttributeError from accessing attributes of the Parent object (i.e. typo on interactive interpreter), Python reports a leak of its member on exit. I expect no memory leak.

I observe this behavior on Python 3.11 and 3.12 with nanobind 1.8.0.

Minimal example is below:

### Reproducible example code

```text
// module.cpp
#include <nanobind/nanobind.h>
#include <nanobind/stl/shared_ptr.h>
#include <memory>

struct A {};
struct B {
  const std::shared_ptr<A> a_;
  B(std::shared_ptr<A> a) : a_{a} {}
};

namespace nanobind = nb;

NB_MODULE(nanobind_example, m) {
  nb::class_<A>(m, "A").def(nb::init<>());
  nb::class_<B>(m, "B").def(nb::init<std::shared_ptr<A>>());
}

// end module.cpp

# Python REPL

>>> from nanobind_example import A, B
>>> B(A()).foo

AttributeError: 'B' object has no attribute 'foo'

>>> exit()

nanobind: leaked 1 instances!
nanobind: leaked 1 types!
 - leaked type "nanobind_example.A"
nanobind: leaked 1 functions!
 - leaked function "__init__"
nanobind: this is likely caused by a reference counting issue in the binding code.
```

**Comment by wjakob** [comment]
Please see https://nanobind.readthedocs.io/en/latest/faq.html#why-am-i-getting-errors-about-leaked-functions-and-types. To further classify this issue, could you try the following:

- Does he leak still occur when you move your code from the global level into a function that you call from the global level?
- If it still occurs, also do a `import gc; gc.collect()` after the function returns.

**Comment by jaicher** [comment]
> Does the leak still occur when you move your code from the global level into a function that you call from the global level?

The leak still occurs.

> If it still occurs, also do a import gc; gc.collect() after the function returns.

The leak still occurs when running gc.collect() after the function returns.

If it helps to classify the issue, I made the following additional observations:

* if I handle the exception --> no more leak message
* if I catch the exception but then raise any other exception --> still get leak message

```python
try:
    B(A()).foo
except Exception:
    # raise  # (leak message)
    # raise ValueError("unrelated error")  # (leak message)
    pass # no leak message
```

(not sure how relevant `sys.getrefcount()` is, but I observed that if I store the values (`a = A(); b = B(b)`), each time that an AttributeError is raised and unhandled on `b.foo`, `b`'s refcount is incremented by 1 (if handled, there is no change). This appears to be true for other Python objects as well, though (list, tuple, arbitrary Python class, etc.).)

**Comment by jaicher** [comment]
If I run `gc.collect()` after a second, unrelated exception is raised, A and B's destructors are run at that time.

I think the reason it needs a second, unrelated exception to be raised is because Python keeps the last raised exception in memory for post-mortem debugging for interactive sessions. And, to enable this debugging, Python also keeps the object in question in memory.

Not really sure why B's destructor is called but not A's in this case.  However, if we emulate A and B in Python, **neither** destructor is called:

```python
class A(object):
    def __del__(self): print("~A")
class B(object):
    def __init__(self, a): self.a = a
    def __del__(self): print("~B")

>>> B(A()).foo
AttributeError {...}
>>> exit()
# never get message from destructors
```

Since the garbage collector can clean it up after the second exception, and there are reasons we would want to keep the objects in memory in the context of the first exception, I am no longer worried about this behavior and think it is probably benign.

**Comment by wjakob** [comment]
What Python version are you on? I think a few rare GC-related leaks at shutdown time like the one you are describing were fixed in 3.12. I'd be curious to hear if that fixes it.

**Comment by jaicher** [comment]
The problem persists in Python 3.12: if an AttributeError on `B` is the last unhandled exception, the destructor of its member `a_` is never run.

The garbage collector appears more eager, though. The destructors for B and A are run immediately after a second exception is raised (vs running on exit or manually running `gc.collect()`)
